version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    environment:
      - "KEYCLOAK_ADMIN=admin"
      - "KEYCLOAK_ADMIN_PASSWORD=admin"
      - "KEYCLOAK_IMPORT=/opt/keycloak/data/import/realm-export.json"
      - "KC_HEALTH_ENABLED=true"
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
    command:
      - "start-dev"
      - "--http-port=8080"
      - "--import-realm"
    ports:
      - 8080:8080
    healthcheck:
      test: ["CMD-SHELL", "exec 3<>/dev/tcp/127.0.0.1/8080;echo -e \"GET /health/ready HTTP/1.1\r\nhost: http://localhost\r\nConnection: close\r\n\r\n\" >&3;grep \"HTTP/1.1 200 OK\" <&3"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  import-users:
    build:
      context: ./keycloak
      dockerfile: Dockerfile.utility
    command: "/opt/jboss/keycloak/imports/import-users.sh"
    volumes:
      - ./keycloak/import-users.sh:/opt/jboss/keycloak/imports/import-users.sh
    depends_on:
      keycloak:
        condition: service_healthy
  
  setup-backend-client:
    build:
      context: ./keycloak
      dockerfile: Dockerfile.utility
    command: "/opt/jboss/keycloak/imports/setup_client_secret.sh"
    volumes:
      - ./keycloak/setup_client_secret.sh:/opt/jboss/keycloak/imports/setup_client_secret.sh
    depends_on:
      keycloak:
        condition: service_healthy

  db:
    image: postgres
    environment:
      POSTGRES_USER: curio
      POSTGRES_PASSWORD: curio
    ports:
      - 5432:5432

  strapi:
    container_name: strapi
    build:
      context: ./strapi
      dockerfile: Dockerfile.strapi
    image: strapi:latest
    restart: unless-stopped
    env_file: ./strapi/.env
    environment:
      # DATABASE_CLIENT: ${DATABASE_CLIENT}
      # DATABASE_HOST: strapiDB
      # DATABASE_PORT: ${DATABASE_PORT}
      # DATABASE_NAME: ${DATABASE_NAME}
      # DATABASE_USERNAME: ${DATABASE_USERNAME}
      # DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      # JWT_SECRET: ${JWT_SECRET}
      # ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      # APP_KEYS: ${APP_KEYS}
      NODE_ENV: development
    volumes:
      - ./strapi/config:/opt/app/config
      - ./strapi/src:/opt/app/src
      - ./strapi/package.json:/opt/package.json
      - ./strapi/.env:/opt/app/.env
      - ./strapi/public/uploads:/opt/app/public/uploads
    ports:
      - "1337:1337"
    